//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recyclebin2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favList
    {
        public int cartID { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> bill { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> qty { get; set; }
    }
}
