//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recyclebin2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestingSdProjectDBEntities2 : DbContext
    {
        public TestingSdProjectDBEntities2()
            : base("name=TestingSdProjectDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Catagory> Catagories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<favList> favLists { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserUpload> UserUploads { get; set; }
    }
}
